USE DATABASE CORE_TELECOMS;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE AGENTS_RAW (data VARIANT);
CREATE OR REPLACE TABLE CALL_CENTER_LOGS_RAW (data VARIANT);
CREATE OR REPLACE TABLE CUSTOMERS_RAW (data VARIANT);
CREATE OR REPLACE TABLE SOCIAL_MEDIA_RAW (data VARIANT);
CREATE OR REPLACE TABLE WEBSITE_COMPLAINTS_RAW (data VARIANT);

SHOW TABLES;

SELECT data FROM RAW.CUSTOMERS_RAW LIMIT 5;

SELECT COUNT(*) FROM raw.agents_raw


USE DATABASE CORE_TELECOMS;
USE SCHEMA CURATED;

SHOW TABLES;

SELECT * 
FROM AGENTS
LIMIT 10;
