CREATE DATABASE IF NOT EXISTS CORE_TELECOMS;
USE DATABASE CORE_TELECOMS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE ROLE IF NOT EXISTS ETL_ROLE;

-- Create a user for Airflow/dbt (replace password with a secure value)
CREATE USER IF NOT EXISTS ETL_USER
  PASSWORD = '*********'
  DEFAULT_ROLE = ETL_ROLE
  DEFAULT_WAREHOUSE = CORE_ETL_WH
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service user for Airflow & dbt';

GRANT ROLE ETL_ROLE TO USER ETL_USER;

GRANT USAGE ON WAREHOUSE CORE_ETL_WH TO ROLE ETL_ROLE;
GRANT USAGE ON DATABASE CORE_TELECOMS TO ROLE ETL_ROLE;
GRANT USAGE ON SCHEMA CORE_TELECOMS.RAW TO ROLE ETL_ROLE;
GRANT USAGE ON SCHEMA CORE_TELECOMS.CURATED TO ROLE ETL_ROLE;
GRANT USAGE ON SCHEMA CORE_TELECOMS.GOLD TO ROLE ETL_ROLE;

GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA CORE_TELECOMS.RAW TO ROLE ETL_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CORE_TELECOMS.CURATED TO ROLE ETL_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA CORE_TELECOMS.GOLD TO ROLE ETL_ROLE;